// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8cZcsxi4-iKHbuDIhBcaxNI1sNA9rWIM',
    appId: '1:46132656723:web:c70232d93969381e3864a6',
    messagingSenderId: '46132656723',
    projectId: 'read-learn',
    authDomain: 'read-learn.firebaseapp.com',
    storageBucket: 'read-learn.appspot.com',
    measurementId: 'G-BZC2P6BGYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiKY2jS3Iw1ePEIFooW9wdLGHnCxD5NkU',
    appId: '1:46132656723:android:f849bffc0843f3613864a6',
    messagingSenderId: '46132656723',
    projectId: 'read-learn',
    storageBucket: 'read-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFSCEw_esGtRlXp8M-OHRYQfZf4hH_W8c',
    appId: '1:46132656723:ios:7a42810410f91e163864a6',
    messagingSenderId: '46132656723',
    projectId: 'read-learn',
    storageBucket: 'read-learn.appspot.com',
    iosBundleId: 'com.vscoracademy.read',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFSCEw_esGtRlXp8M-OHRYQfZf4hH_W8c',
    appId: '1:46132656723:ios:7a42810410f91e163864a6',
    messagingSenderId: '46132656723',
    projectId: 'read-learn',
    storageBucket: 'read-learn.appspot.com',
    iosBundleId: 'com.vscoracademy.read',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8cZcsxi4-iKHbuDIhBcaxNI1sNA9rWIM',
    appId: '1:46132656723:web:09ff44159c46a14a3864a6',
    messagingSenderId: '46132656723',
    projectId: 'read-learn',
    authDomain: 'read-learn.firebaseapp.com',
    storageBucket: 'read-learn.appspot.com',
    measurementId: 'G-N7WKNY01YN',
  );
}
